blank_issues_enabled: false
contact_links:
  - name: Bit.new related issues
    url: https://github.com/stackblitz/bit.new/issues/new/choose
    about: Report issues related to Bit.new (not Bit.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Bit.diy users.
